train_binary_models: True
train_multiclass_models: True
debug: False
save_models: False

batch_size: 32
patience: False
num_workers: 30
auto_lr_find: False

baseline_models_to_train: ["xvector", "egemaps", "compare", "aggregated_mfccs", "xlsr-danish", "xlsr"] # wav2vec embedding, 
wav2vec_model_ids: ["placeholder"]

augmentations:
  transform: Compose
  params:
    shuffle: True
    p: 1
    transforms:
      - transform: Gain
        params:
          p: 0.5
      - transform: AddColoredNoise
        params:
          p: 0.5
      - transform: ApplyImpulseResponse
        params:
          ir_paths: augmentation_files/ir/Audio
          p: 0.5
      - transform: SpliceOut
        params:
          p: 0.5

pl_trainer_kwargs:
  log_every_n_steps: 1500
  check_val_every_n_epoch: 1
  gpus: -1
  profiler: null
  max_epochs: 1
  precision: 16
  auto_lr_find: False

model_kwargs:
  learning_rate: 0.0005
